### ISSUE TITLE
stylesSet entries with class attributes values behaves differently between 4.7.1 and 4.10.1

### ISSUE THREAD

**Issue by josefglatz** [ckeditor/ckeditor-dev#2578]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

A detailed explanation could be found in the issue on the [TYPO3 CMS issue tracker](https://forge.typo3.org/issues/86852) 

If you define the following stylesSet configuration:

```yaml
editor:
  config:
    stylesSet:
      - { name: 'Button', element: 'a', attributes: { class: 'button button--primary'} }
      - { name: 'Small button', element: 'a', attributes: { class: 'button button--primary button--small'} }
      - { name: 'Big button', element: 'a', attributes: { class: 'button button--primary button--big'} }
```
the stylesSet item named *Big button* is not shown in CKEditor 4.10.1 (in CKEditor 4.7.1 it's working as expected)

### Expected result

After an upgrade of CKEditor > 4.7.1 the button must be shown in the styles dropdown

### Actual result

The stylesSet item *Big button* isn't shown in the Styles selectbox
